server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:h2:tcp://localhost:3306/mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
#    username: root
#    password: Bemvindo@digital
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#        hibernate:
#            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:h2:mem:testdb
    schemas: cambio_service
    user: sa
    password: Bemvindo@digital